subprojects:
  - id: common
    paths:
      - "**"
    checks:
      - "WIP"
      - "task-list-completed"
  - id: documentation
    paths:
      - "README.md"
      - "docs/README.md"
      - "CONTRIBUTING.md"
      - "docs/development.md"
    checks:
      - "readme-sync"
  - id: server
    paths:
      - "src/**"
    checks:
      - "server-test"
