name: File Sync
on: [pull_request]
jobs:
  readme-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tianhaoz95/mirror-action@v1.0.1
        with:
          original: "README.md"
          mirror: "docs/README.md"
      - uses: tianhaoz95/mirror-action@v1.0.1
        with:
          original: "CONTRIBUTING.md"
          mirror: "docs/development.md"
