name: File Sync
on: push
jobs:
  readme-sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: tianhaoz95/mirror-action@v1.0.1
        with:
          original: "README.md"
          mirror: "docs/README.md"
      - uses: tianhaoz95/mirror-action@v1.0.1
        with:
          original: "CONTRIBUTING.md"
          mirror: "docs/development.md"
