name: Publish CLI
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  publish-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v3
        if: >-
          github.actor != 'dependabot[bot]' &&
          github.actor != 'dependabot-preview[bot]' &&
          github.event_name == 'push'
        with:
          token: ${{ secrets.USE_GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com/@tianhaoz95
