name: Publish Image
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        if: >-
          github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.USE_GITHUB_TOKEN }}
      - name: get_tag
        id: get_tag
        working-directory: scripts/bash
        env:
          USERNAME: ${{ github.repository_owner }}
        run: |
          source query_image_tag.sh
          echo "::set-output name=image_tag::ghcr.io/$USERNAME/approveman-server:$USE_TAG_NAME"
      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.get_tag.outputs.image_tag }}
