name: Publish CLI
on:
  pull_request_target:
    types: [labeled, synchronize, reopened]
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  publish-cli:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' || 
        contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        if: >-
          github.actor != 'dependabot[bot]' &&
          github.actor != 'dependabot-preview[bot]'
        with:
          token: ${{ secrets.USE_GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com/@tianhaoz95
          dry-run: ${{ github.event_name == 'pull_request_target' }}
