name: Publish Image
on:
  pull_request_target:
    types: [labeled, synchronize, reopened]
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  publish-image:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' || 
        contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.2"
      - run: npm install
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        if: >-
          github.actor != 'dependabot[bot]' &&
          github.actor != 'dependabot-preview[bot]'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.USE_GITHUB_TOKEN }}
      - name: get_tag
        id: get_tag
        working-directory: scripts/bash
        if: >-
          github.actor != 'dependabot[bot]' &&
          github.actor != 'dependabot-preview[bot]'
        env:
          USERNAME: ${{ github.repository_owner }}
        run: |
          source query_image_tag.sh
          echo "::set-output name=image_tag::ghcr.io/$USERNAME/approveman-server:$USE_TAG_NAME"
      - uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          push: true
          tags: ${{ steps.get_tag.outputs.image_tag }}
      - uses: docker/build-push-action@v2
        if: >-
          github.event_name == 'pull_request_target' && 
          github.actor != 'dependabot[bot]' &&
          github.actor != 'dependabot-preview[bot]'
        with:
          push: false
          tags: ${{ steps.get_tag.outputs.image_tag }}
